services:
  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    environment:
      - SERVER_PORT=8081
    volumes:
      - ./aas:/application/aas
      - ./basyx/aas-env.properties:/application/application.properties
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
      mongo:
        condition: service_healthy
      mosquitto:
        condition: service_healthy
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - '8082:8080'
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./basyx/aas-registry.yml:/workspace/config/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    container_name: sm-registry
    ports:
      - '8083:8080'
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./basyx/sm-registry.yml:/workspace/config/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
  aas-web-ui:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    container_name: aas-ui
    ports:
      - '3000:3000'
    environment:
      AAS_REGISTRY_PATH: http://localhost:8082/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://localhost:8083/submodel-descriptors
      AAS_REPO_PATH: http://localhost:8081/shells
      SUBMODEL_REPO_PATH: http://localhost:8081/submodels
      CD_REPO_PATH: http://localhost:8081/concept-descriptions
      AAS_DISCOVERY_PATH: http://localhost:8084/lookup/shells
      LOGO_PATH: Konecranes-logo.jpg
      DASHBOARD_SERVICE_PATH: http://localhost:8085/api/elements
      ALLOW_EDITING: "true"
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy
    volumes:
      - ./logo:/usr/src/app/dist/Logo

  opcua-operation-service:
    build:
      context: ./opcua-operation-service
      dockerfile: Dockerfile
    container_name: opcua-operation-service
    environment:
      - OPCUA_ENDPOINT=opc.tcp://10.210.1.12:4840
      - OPCUA_AUTH_MODE=anonymous
      - OPCUA_USERNAME=
      - OPCUA_PASSWORD=
      - OPCUA_SECURITY_MODE=None
      - OPCUA_SECURITY_POLICY=None
      - OPCUA_PULSE_EDGE_TRIGGER_ENABLED=false
      - OPCUA_PULSE_LEADING_FALSE_DELAY_MS=100
      - OPCUA_WRITE_BOOLEAN_NUMERIC_FALLBACK_ENABLED=true
      - OPCUA_ACCESS_CODE=
      - OPCUA_WATCHDOG_INCREMENT_ENABLED=false
    ports:
      - '8087:8087'
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
#ALTERNATIVE OPTION: If you want to run the opcua-aas-bridge as a separate service, you can uncomment the following section and make sure to adjust the environment variables accordingly. 
# This will allow the bridge to connect to the OPC UA server running on the host machine and the AAS environment running in the container.
 # opcua-aas-bridge:
 #   build:
 #     context: ./opcua-aas-bridge
 #     dockerfile: Dockerfile
 #   container_name: opcua-aas-bridge
 #   environment:
 #     - OPCUA_ENDPOINT=opc.tcp://host.docker.internal:4840
 #     - AAS_ENDPOINT=http://aas-env:8081
 #   restart: always
 #   extra_hosts:
 #     - "host.docker.internal:host-gateway"
 #   depends_on:
 #     aas-env:
 #       condition: service_healthy
  
  aas-discovery:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    container_name: aas-discovery
    environment:
      - SERVER_PORT=8081
    volumes:
      - ./basyx/aas-discovery.properties:/application/application.properties
    ports:
      - '8084:8081'
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:5.0.10
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: always
    healthcheck:
      test: mongo
      interval: 10s
      timeout: 5s
      retries: 5
  mosquitto:
    image: eclipse-mosquitto:2.0.15
    container_name: mosquitto
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto:/mosquitto
    restart: always
    healthcheck:
      test:
        - CMD-SHELL
        - mosquitto_sub -p 1883 -t 'topic' -C 1 -E -i probe -W 3
      interval: 5s
      timeout: 10s
      start_period: 1s
      retries: 3
  dashboard-api:
    image: aaronzi/basyx-dashboard-api:SNAPSHOT_02
    container_name: dashboard-api
    ports:
      - '8085:8085'
    volumes:
      - ./basyx/aas-dashboard.yml:/application.yml
    restart: always
    depends_on:
      mongo:
        condition: service_healthy
  databridge:
    image: eclipsebasyx/databridge:1.0.0-milestone-08
    container_name: databridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./databridge:/usr/share/config
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy


